### ISSUE TITLE
请教博客模板

### ISSUE THREAD

**Issue by Pabebezz** [RoseSnow/RoseSnow.github.io#1]
大佬，您好。
     不好意思，打扰您了~
       我从CSDN上“手把手教你在Github上建立自己的个人博客网站”跟过来的，您的博客太好了，布局清晰明了，动态效果也很赞~~
        萌新能请教一下您的博客是基于Hexo的吗？能否借用您的模板呢？

**Comment by amagnatema** [comment]
兄弟言重了，很抱歉没及时看到回复你，现在你博客应该已经搭好了吧，我的使用的hexo得模板，有些配置我博客有几篇文章写到
